"""Add last_full_sync to accounts

Revision ID: 176eb40fe1ae
Revises: 20260504_03
Create Date: 2026-05-09 12:25:11.939253
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176eb40fe1ae'
down_revision: Union[str, None] = '20260504_03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_full_sync', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_full_sync')
    # ### end Alembic commands ###
